export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
export { default as Portfolio } from "./Portfolio";
export { default as ContactUs } from "./ContactUs";
export { default as About } from "./About";
export { default as Resume } from "./Resume";
export { default as GalleryForPortfolio } from "./GalleryForPortfolio";
export { default as ResumeForDesign } from "./ResumeForDesign";
export { default as GalleryFullPortfolio } from "./GalleryFullPortfolio";